key_name                 = ""
db_username              = ""
db_password              = ""
nextcloud_admin_user     = ""
nextcloud_admin_password = ""
route53_zone_id          = ""
domain_name              = ""
subdomain                = ""